# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ccc6cff57180a56edcdf79cd0fd968393d173e8bf7b763c46c4e792fbbaf34b050a645032440be4970dfe02bd9fad93b144efc7728cb66d75f8e2efff8a1b7e

test:
  secret_key_base: 6409a23527092ad808134a1df11ac552bfe33a7c0a53b0a46478fb0e0a5deb0584d2f6e99406e34e4a201114e5d532f0d67ef4b592b71bf45c815ab8a6bc3588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
